# Generated by Django 4.0.6 on 2022-08-01 00:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categorys_images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('full_name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Full name')),
                ('email', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Adresse')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qualification')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='password')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students_avatar', verbose_name='Photo')),
                ('interested_category', models.TextField(blank=True, null=True, verbose_name='Interested category')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('full_name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Full name')),
                ('email', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Adresse')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qualification')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='password')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers_avatar', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cours_images', verbose_name='Image')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_category', to='formation.coursecategory', verbose_name='Category')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_teacher', to='formation.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('pourcentage', models.IntegerField(blank=True, null=True, verbose_name='Pourcentage')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_teacher_competence', to='formation.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Competences',
            },
        ),
    ]
