# Generated by Django 4.1 on 2022-08-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Competence'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Category Cours', 'verbose_name_plural': 'Categorys Cours'},
        ),
    ]
