# Generated by Django 4.0.4 on 2022-05-26 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_formation', '0010_remove_tutoriel_niveau_alter_cours_plublish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 10, 33, 20, 991668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 10, 33, 20, 991668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutoriel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tutoriel',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 10, 33, 20, 991668, tzinfo=utc)),
        ),
    ]
