# Generated by Django 4.0.4 on 2022-05-30 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_quill.fields
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_formation', '0018_alter_formation_plublish_alter_lecon_plublish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations', verbose_name='Image')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('plublish', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 22, 56, 29, 853497, tzinfo=utc))),
                ('published', models.BooleanField(default=False, verbose_name='Publie')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Cour',
            },
        ),
        migrations.AlterField(
            model_name='formation',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 22, 56, 29, 853497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutoriel',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 22, 56, 29, 869118, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Lecon',
        ),
        migrations.AddField(
            model_name='cours',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_formations', to='app_formation.formation', verbose_name='Formations'),
        ),
    ]
