# Generated by Django 4.0.6 on 2022-07-15 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100, verbose_name='Libelle')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('sujet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grade', models.CharField(max_length=200, verbose_name='nom_grade')),
            ],
            options={
                'verbose_name': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_specialite', models.CharField(max_length=200, verbose_name='Nom_specialite')),
            ],
            options={
                'verbose_name': 'Specialite',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignage_photo', verbose_name='Photo')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.specialite', verbose_name='Specialite')),
            ],
            options={
                'verbose_name': 'Temoignage',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teams', verbose_name='Photo')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('linkdin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkdin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.grade', verbose_name='Grade')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.specialite', verbose_name='Specialite')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('date_projet', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date projet')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Url')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image3')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_portfolio', to='app_web.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_blog_comment', to='app_web.blogtags')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('description1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description1')),
                ('description2', django_quill.fields.QuillField(blank=True, max_length=200, null=True, verbose_name='Description2')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images', verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('published', models.BooleanField(default=False, verbose_name='Statut')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie', to='app_web.categorie', verbose_name='Categorie')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_blog_tags', to='app_web.blogtags')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-created'],
            },
        ),
    ]
