# Generated by Django 4.0.6 on 2022-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('bts', 'BTS'), ('licence', 'Licence'), ('autre', 'Autre'), ('master', 'Master'), ('doctorat', 'Doctorat')], default='corbeille', max_length=200, verbose_name='Statut'),
        ),
    ]
