# Generated by Django 4.0.6 on 2023-03-05 13:45

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('adresse', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Adresse')),
                ('annee', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Annee')),
                ('formation', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Formation')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('ecole', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Université')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_avatar', verbose_name='Photo')),
                ('specialite', models.CharField(blank=True, max_length=200, null=True, verbose_name='specialite')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('linkdin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkdin')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='name')),
                ('first_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('username', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('is_auteur', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_membre', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
    ]
