# Generated by Django 4.1 on 2022-08-05 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutoriels', verbose_name='Poster')),
                ('url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publie')),
                ('plublish', models.DateTimeField(default=datetime.datetime(2022, 8, 5, 9, 35, 54, 716498, tzinfo=datetime.timezone.utc))),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_user_tuto', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_category_tuto', to='main.articlecategorie', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Tutoriel',
                'ordering': ['-updated'],
            },
        ),
    ]
