# Generated by Django 4.1 on 2022-08-05 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriel', '0002_alter_tutoriel_plublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriel',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 17, 4, 44, 984646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tutoriel',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
