# Generated by Django 4.1 on 2022-08-05 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriel', '0003_alter_tutoriel_plublish_alter_tutoriel_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriel',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 17, 8, 11, 42558, tzinfo=datetime.timezone.utc)),
        ),
    ]
