# Generated by Django 4.1 on 2022-08-07 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriel', '0007_alter_tutoriel_plublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriel',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 1, 14, 44, 470337, tzinfo=datetime.timezone.utc)),
        ),
    ]
