# Generated by Django 4.0.4 on 2022-05-21 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_quill.fields
import embed_video.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('desc1', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Desc1')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('published', models.BooleanField(default=False, verbose_name='Publie')),
                ('plublish', models.DateTimeField(default=datetime.datetime(2022, 5, 21, 11, 11, 20, 109861, tzinfo=utc))),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie', to='app_formation.category', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('sujet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Poster')),
                ('url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('lieu', models.CharField(max_length=100, verbose_name='Lieu')),
                ('dateEv', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Evenement',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
            ],
            options={
                'verbose_name': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'NewsLetter',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Photo')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('status', models.BooleanField(default='True', verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Slider',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
            ],
            options={
                'verbose_name': 'Specialite',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignage', verbose_name='Photo')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Temoignage',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teams', verbose_name='Photo')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('linkdin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkdin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.grade', verbose_name='Grade')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.specialite', verbose_name='Specialite')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('plublish', models.DateTimeField(default=datetime.datetime(2022, 5, 21, 11, 11, 20, 109861, tzinfo=utc))),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_article', to='app_web.article', verbose_name='Article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
    ]
