# Generated by Django 4.0.4 on 2022-05-23 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temoignage',
            name='titre',
        ),
        migrations.AddField(
            model_name='temoignage',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.specialite', verbose_name='Specialite'),
        ),
        migrations.AlterField(
            model_name='article',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 6, 24, 51, 689981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 6, 24, 51, 689981, tzinfo=utc)),
        ),
    ]
