# Generated by Django 4.0.4 on 2022-05-26 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_remove_contact_phone_alter_article_plublish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 8, 10, 17, 440431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='plublish',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 8, 10, 17, 440431, tzinfo=utc)),
        ),
    ]
