# Generated by Django 4.0.4 on 2022-05-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_customeruser_nom_customeruser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='slug',
        ),
    ]
