# Generated by Django 4.1.1 on 2022-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_customeruser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='grade',
            field=models.TextField(blank=True, choices=[('master', 'Master'), ('doctorat', 'Doctorat'), ('bts', 'BTS'), ('autre', 'Autre'), ('licence', 'Licence')], null=True, verbose_name='Grade'),
        ),
    ]
