# Generated by Django 4.0.6 on 2023-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='mode_payement',
            field=models.CharField(choices=[('transfere_flooz', 'FlOOZ'), ('espece', 'Espece'), ('transfere_tmoney', 'TMONEY')], max_length=200, verbose_name='Mode de payement'),
        ),
    ]
